package server

import (
	"context"
	"database/sql"
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/my-pets/api/internal/auth"
	"github.com/my-pets/api/internal/config"
	"github.com/my-pets/api/internal/health"
	"github.com/my-pets/api/internal/middleware"
	"github.com/my-pets/api/internal/pet"
	"github.com/my-pets/api/internal/setup"
	"github.com/my-pets/api/internal/user"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/my-pets/api/docs" // generated by swag init
)

// Run wires up all dependencies and starts the HTTP server.
// It blocks until the server exits or an error occurs.
func Run(cfg *config.Config, db *sql.DB) {
	ctx := context.Background()

	// Run migrations for each domain.
	if err := pet.Migrate(ctx, db); err != nil {
		log.Fatalf("pet migration failed: %v", err)
	}
	if err := user.Migrate(ctx, db); err != nil {
		log.Fatalf("user migration failed: %v", err)
	}
	log.Println("Migrations applied")

	// Set Gin mode before creating the engine.
	if cfg.GinMode == "release" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.Default()
	r.Use(middleware.CORS())

	// Health check (no versioning prefix)
	r.GET("/health", health.Handler)

	// Swagger UI
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Shared repositories
	userRepo := user.NewPostgresRepo(db)

	// Versioned API root group
	v1 := r.Group("/api/v1")

	// ── Public routes (no JWT) ──────────────────────────────────────────────
	// Setup endpoints (must be registered before auth, publicly accessible)
	setupHandler := setup.NewHandler(userRepo)
	setup.RegisterRoutes(v1, setupHandler)

	// Auth endpoints that are public
	authHandler := auth.RegisterRoutes(v1, cfg, userRepo)

	// ── Protected routes (JWT required) ─────────────────────────────────────
	protected := v1.Group("", middleware.JWT(cfg))
	{
		// Auth endpoints that need the caller to be authenticated
		auth.RegisterProtectedRoutes(protected, authHandler)

		// Pet domain
		petRepo := pet.NewPostgresRepo(db)
		petHandler := pet.NewHandler(petRepo)
		pet.RegisterRoutes(protected, petHandler)

		// User domain
		userHandler := user.NewHandler(userRepo)
		user.RegisterRoutes(protected, userHandler)
	}

	log.Printf("Server running on :%s", cfg.Port)
	if err := r.Run(":" + cfg.Port); err != nil && err != http.ErrServerClosed {
		log.Fatalf("Server error: %v", err)
	}
}
