package server

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/my-pets/api/internal/config"
	"github.com/my-pets/api/internal/database"
	domainAuth "github.com/my-pets/api/internal/domain/auth"
	"github.com/my-pets/api/internal/domain/health"
	domainPet "github.com/my-pets/api/internal/domain/pet"
	domainSetup "github.com/my-pets/api/internal/domain/setup"
	domainUser "github.com/my-pets/api/internal/domain/user"
	"github.com/my-pets/api/internal/middleware"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/gorm"

	_ "github.com/my-pets/api/docs" // generated by swag init
)

// Run wires up all dependencies and starts the HTTP server.
// It blocks until the server exits or an error occurs.
func Run(cfg *config.Config, db *gorm.DB) {
	// Run AutoMigrate for all models.
	if err := database.Migrate(db); err != nil {
		log.Fatalf("migration failed: %v", err)
	}
	log.Println("Migrations applied")

	// Set Gin mode before creating the engine.
	if cfg.GinMode == "release" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.Default()
	r.Use(middleware.CORS())

	// Health check (no versioning prefix)
	r.GET("/health", health.Handler)

	// Swagger UI
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Shared repositories
	userRepo := domainUser.NewGormRepo(db)

	// Versioned API root group
	v1 := r.Group("/api/v1")

	// ── Public routes (no JWT) ──────────────────────────────────────────────
	// Setup endpoints (must be registered before auth, publicly accessible)
	setupHandler := domainSetup.NewHandler(userRepo)
	domainSetup.RegisterRoutes(v1, setupHandler)

	// Auth endpoints that are public
	authHandler := domainAuth.RegisterRoutes(v1, cfg, userRepo)

	// ── Protected routes (JWT required) ─────────────────────────────────────
	protected := v1.Group("", middleware.JWT(cfg))
	{
		// Auth endpoints that need the caller to be authenticated
		domainAuth.RegisterProtectedRoutes(protected, authHandler)

		// Pet domain
		petRepo := domainPet.NewGormRepo(db)
		petHandler := domainPet.NewHandler(petRepo)
		domainPet.RegisterRoutes(protected, petHandler)

		// User domain
		userHandler := domainUser.NewHandler(userRepo)
		domainUser.RegisterRoutes(protected, userHandler)
	}

	log.Printf("Server running on :%s", cfg.Port)
	if err := r.Run(":" + cfg.Port); err != nil && err != http.ErrServerClosed {
		log.Fatalf("Server error: %v", err)
	}
}
